version = 1

test_patterns = ["test/**"]

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = ["Dockerfile"]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"
