### Ports
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
    endpoint:
      health:
        show-details: always

spring:
  ### Profiles
  profiles:
    active: textlogs

  ### Turn off Spring Boot banner
  main:
    banner-mode: off


twitter-account-properties:
  accounts:
    - name: stupidAccount
      search: stupidSearchThatHopefullyNeverMatches
      location-search: stupidLocationSearchThatHopefullyNeverMatches
      location-to-follow: stupidLocationToFollowThatHopefullyNeverMatches
      ignored-accounts:
        - stupidAccount1ThatHopefullyNeverMatches
        - stupidAccount2ThatHopefullyNeverMatches
      account-api-config:
        bearerToken: stupidbearerToken
        twitter4j:
          oauth:
            accessToken: stupidAccessToken
            accessTokenSecret: stupidAccessTokenSecret
            consumerKey: stupidConsumerKey
            consumerSecret: stupidConsumerSecret
    - name: stupidAccount
      search: stupidSearchThatHopefullyNeverMatches
      location-search: stupidLocationSearchThatHopefullyNeverMatches
      location-to-follow: stupidLocationToFollowThatHopefullyNeverMatches
      ignored-accounts:
        - stupidAccount1ThatHopefullyNeverMatches
        - stupidAccount2ThatHopefullyNeverMatches
      account-api-config:
        bearerToken: stupidbearerToken
        twitter4j:
          oauth:
            accessToken: stupidAccessToken
            accessTokenSecret: stupidAccessTokenSecret
            consumerKey: stupidConsumerKey
            consumerSecret: stupidConsumerSecret
