### Ports
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /
    endpoint:
      health:
        show-details: always

spring:
  ### Profiles
  profiles:
    active: textlogs

  ### Turn off Spring Boot banner
  main:
    banner-mode: off


account-properties:
  twitter:
    ignored-accounts:
    accounts:
      - name: stupidAccount
        bearerToken: stupidbearerToken
        twitter4j:
          oauth:
            accessToken: stupidAccessToken
            accessTokenSecret: stupidAccessTokenSecret
            consumerKey: stupidConsumerKey
            consumerSecret: stupidConsumerSecret
        search: stupidSearchThatHopefullyNeverMatches
        location-search: stupidLocationSearchThatHopefullyNeverMatches
        location-to-follow: stupidLocationToFollowThatHopefullyNeverMatches
        ignored-accounts:
          - stupidAccount1ThatHopefullyNeverMatches
          - stupidAccount2ThatHopefullyNeverMatches
      - name: stupidAccount
        bearerToken: stupidbearerToken
        twitter4j:
          oauth:
            accessToken: stupidAccessToken
            accessTokenSecret: stupidAccessTokenSecret
            consumerKey: stupidConsumerKey
            consumerSecret: stupidConsumerSecret
        search: stupidSearchThatHopefullyNeverMatches
        location-search: stupidLocationSearchThatHopefullyNeverMatches
        location-to-follow: stupidLocationToFollowThatHopefullyNeverMatches
        ignored-accounts:
          - stupidAccount1ThatHopefullyNeverMatches
          - stupidAccount2ThatHopefullyNeverMatches
  mastodon:
    ignored-accounts:
    accounts:
      - name: stupidAccount
        instance: stupidInstance
        oauth:
          accessToken: stupidAccessToken
          accessTokenSecret: stupidAccessTokenSecret
        redirectUri: stupidRedirectUri
        location-search: stupidLocationSearchThatHopefullyNeverMatches
        location-to-follow: stupidLocationToFollowThatHopefullyNeverMatches
        ignored-accounts:
          - stupidAccount1ThatHopefullyNeverMatches
          - stupidAccount2ThatHopefullyNeverMatches
